import type { Scenario, ScenarioCategory } from '@/types';

export const CATEGORY_LABELS: Record<ScenarioCategory, string> = {
  workplace: 'Công sở',
  survival: 'Sinh hoạt',
  social: 'Giao tiếp',
  travel: 'Du lịch',
  academic: 'Học thuật',
  industry: 'Theo ngành',
};

export const CATEGORY_ORDER: ScenarioCategory[] = [
  'workplace',
  'social',
  'travel',
  'survival',
  'academic',
  'industry',
];

export const SCENARIOS: Scenario[] = [
  {
    id: 'sc-coffee',
    title: 'Order coffee at a café',
    titleVi: 'Gọi cà phê',
    category: 'survival',
    level: 'A1',
    durationMin: 5,
    goal: 'Order a drink, ask about size and milk options',
    iconEmoji: '☕',
    isGenerated: false,
    systemPrompt: '',
    keyPhrases: [
      { id: 'kp1', english: 'Can I get a latte?', vietnamese: 'Cho tôi một ly latte', ipa: '/kæn aɪ ɡɛt ə ˈlɑːteɪ/' },
      { id: 'kp2', english: 'For here or to go?', vietnamese: 'Uống tại quán hay mang đi?', ipa: '/fɔːr hɪər ɔːr tə ɡoʊ/' },
    ],
  },
  {
    id: 'sc-meeting',
    title: 'Daily standup',
    titleVi: 'Họp standup hàng ngày',
    category: 'workplace',
    level: 'B1',
    durationMin: 8,
    goal: 'Share progress, blockers, and plan',
    iconEmoji: '💼',
    isGenerated: false,
    systemPrompt: '',
    keyPhrases: [
      { id: 'kp1', english: "Yesterday I worked on...", vietnamese: 'Hôm qua tôi làm về...', ipa: '/ˈjɛstərdeɪ aɪ wɜːrkt ɒn/' },
      { id: 'kp2', english: "I'm blocked on...", vietnamese: 'Tôi đang vướng ở...', ipa: '/aɪm blɒkt ɒn/' },
    ],
  },
  {
    id: 'sc-airport',
    title: 'Check-in at the airport',
    titleVi: 'Check-in tại sân bay',
    category: 'travel',
    level: 'A2',
    durationMin: 6,
    goal: 'Check bags, choose seat, ask about gate',
    iconEmoji: '✈️',
    isGenerated: false,
    systemPrompt: '',
    keyPhrases: [
      { id: 'kp1', english: "I'd like a window seat", vietnamese: 'Tôi muốn ghế cạnh cửa sổ', ipa: '/aɪd laɪk ə ˈwɪndoʊ siːt/' },
    ],
  },
  {
    id: 'sc-introduce',
    title: 'Meet a new colleague',
    titleVi: 'Làm quen đồng nghiệp mới',
    category: 'social',
    level: 'A2',
    durationMin: 5,
    goal: 'Introduce yourself, ask about role and team',
    iconEmoji: '👋',
    isGenerated: false,
    systemPrompt: '',
    keyPhrases: [
      { id: 'kp1', english: 'Nice to meet you', vietnamese: 'Rất vui được gặp bạn', ipa: '/naɪs tə miːt juː/' },
      { id: 'kp2', english: 'What team are you on?', vietnamese: 'Bạn ở team nào?', ipa: '/wʌt tiːm ɑːr juː ɒn/' },
    ],
  },
  {
    id: 'sc-restaurant',
    title: 'Make a restaurant reservation',
    titleVi: 'Đặt bàn nhà hàng',
    category: 'survival',
    level: 'A2',
    durationMin: 5,
    goal: 'Book a table, mention preferences',
    iconEmoji: '🍽️',
    isGenerated: false,
    systemPrompt: '',
    keyPhrases: [],
  },
  {
    id: 'sc-interview',
    title: 'Tell me about yourself',
    titleVi: 'Phỏng vấn — giới thiệu bản thân',
    category: 'workplace',
    level: 'B1',
    durationMin: 10,
    goal: 'Introduce background, strengths, why this role',
    iconEmoji: '🎤',
    isGenerated: false,
    systemPrompt: '',
    keyPhrases: [],
  },
  {
    id: 'sc-doctor',
    title: 'At the doctor',
    titleVi: 'Đi khám bệnh',
    category: 'survival',
    level: 'A2',
    durationMin: 6,
    goal: 'Describe symptoms, understand instructions',
    iconEmoji: '🩺',
    isGenerated: false,
    systemPrompt: '',
    keyPhrases: [],
  },
  {
    id: 'sc-presentation',
    title: 'Pitch your idea',
    titleVi: 'Trình bày ý tưởng',
    category: 'workplace',
    level: 'B2',
    durationMin: 12,
    goal: 'Open with hook, walk through structure, close with ask',
    iconEmoji: '📊',
    isGenerated: false,
    systemPrompt: '',
    keyPhrases: [],
  },
];

export const FEATURED_SCENARIO_ID = 'sc-coffee';
